"""empty message

Revision ID: 746f25bc90b9
Revises: dea9480363b6
Create Date: 2019-11-14 17:09:58.995170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746f25bc90b9'
down_revision = 'dea9480363b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
